using System;
using System.Collections.Generic;
using System.Text;

namespace LeagueSandbox.GameServer.Utils.CharacterDatas
{
    public class CharacterData
    {
        //AbilityPowerIncPerLevel
        //AcquisitionRange
        //Armor
        //ArmorPerLevel
        //AttackCastTime
        //AttackDelayCastOffsetPercent
        //AttackDelayCastOffsetPercentAttackSpeedRatio
        //AttackDelayOffsetPercent
        //AttackRange
        //AttackRank
        //AttackSpeed
        //AttackSpeedPerLevel
        //AttackTotalTime
        //BaseAbilityPower
        //BaseAttack_Probability
        //BaseCritChance
        //BaseDamage
        //BaseDodge
        //BaseFactorHPRegen
        //BaseFactorMPRegen
        //BaseHP
        //BaseMP
        //BaseSpellEffectiveness
        //BaseStaticHPRegen
        //BaseStaticMPRegen
        //CritAttack_AttackCastDelayOffsetPercent
        //CritAttack_AttackDelayCastOffsetPercent
        //CritAttack_AttackDelayCastOffsetPercentAttackSpeedRatio
        //CritAttack_AttackDelayOffsetPercent
        //CritAttack_Probability
        //CritDamageBonus
        //CritPerLevel
        //DamagePerLevel
        //DelayCastOffsetPercent
        //DelayTotalTimePercent
        //ExperienceRadius
        //ExpGivenOnDeath
        //ExtraAttack1
        //ExtraAttack1_AttackCastTime
        //ExtraAttack1_AttackDelayCastOffsetPercent
        //ExtraAttack1_AttackDelayOffsetPercent
        //ExtraAttack1_AttackTotalTime
        //ExtraAttack1_Probability
        //ExtraAttack2
        //ExtraAttack2_AttackDelayCastOffsetPercent
        //ExtraAttack2_AttackDelayOffsetPercent
        //ExtraAttack2_Probability
        //ExtraAttack3
        //ExtraAttack3_AttackDelayCastOffsetPercent
        //ExtraAttack3_AttackDelayOffsetPercent
        //ExtraAttack3_Probability
        //ExtraAttack4
        //ExtraAttack4_Probability
        //ExtraAttack5
        //ExtraAttack5_Probability
        //ExtraAttack6
        //ExtraAttack6_Probability
        //ExtraAttack7
        //ExtraAttack7_Probability
        //ExtraAttack8
        //ExtraAttack8_Probability
        //ExtraCritAttack1
        //ExtraCritAttack1_AttackDelayCastOffsetPercent
        //ExtraCritAttack2
        //ExtraCritAttack3
        //ExtraSpell1
        //ExtraSpell10
        //ExtraSpell11
        //ExtraSpell12
        //ExtraSpell13
        //ExtraSpell14
        //ExtraSpell2
        //ExtraSpell3
        //ExtraSpell4
        //ExtraSpell5
        //ExtraSpell6
        //ExtraSpell7
        //ExtraSpell8
        //ExtraSpell9
        //GameplayCollisionRadius
        //GlobalExpGivenOnDeath
        //GlobalGoldGivenOnDeath
        //GoldGivenOnDeath
        //HPPerLevel
        //HPRegenPerLevel
        //ChampionId
        //ChasingAttackRangePercent
        //Immobile
        //IsElite
        //IsEpic
        //IsImportantBotTarget
        //IsMelee
        //Map10_ArmorPerLevel
        //Map10_BaseMP
        //Map8_BaseMP
        //MaxLevels
        //MoveSpeed
        //MPPerLevel
        //MPRegenPerLevel
        //Name
        //NoAutoAttack
        //PARType
        //Passive1
        //Passive1Effect1
        //Passive1Effect2
        //Passive1Effect3
        //Passive1Effect4
        //Passive1Effect5
        //Passive1Level1
        //Passive1Level2
        //Passive1Level3
        //Passive1Level4
        //Passive1Level5
        //Passive1Level6
        //Passive1NumEffects
        //Passive1Range
        //Passive2
        //Passive2Effect1
        //Passive2Effect2
        //Passive2Effect3
        //Passive2Effect4
        //Passive2Level1
        //Passive2Level2
        //Passive2Level3
        //Passive2Level4
        //Passive2NumEffects
        //Passive3
        //Passive3Level1
        //Passive3NumEffects
        //Passive4
        //Passive4Level1
        //Passive4NumEffects
        //PassiveSpell
        //PassLev1Desc1
        //PassLev1Desc2
        //PassLev1Desc3
        //PassLev1Desc4
        //PassLev1Desc5
        //PathfindingCollisionRadius
        //PerceptionBubbleRadius
        //PostAttackMoveDelay
        //RecordAsWard
        //SoulGivenOnDeath
        //Spell1
        //Spell2
        //Spell3
        //Spell4
        //SpellBlock
        //SpellBlockPerLevel
        //SpellsUpLevels1
        //SpellsUpLevels2
        //SpellsUpLevels3
        //SpellsUpLevels4
        //TowerTargetingPriorityBoost
    }
}
